ALTER TABLE public.users
  ADD COLUMN btc_withdrawals_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN trading212_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN coinmate_enabled BOOLEAN NOT NULL DEFAULT TRUE;
