name: run main.py

on:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          T212_ID_KEY: ${{ secrets.T212_ID_KEY }}
          T212_PRIVATE_KEY: ${{ secrets.T212_PRIVATE_KEY }}
          COINMATE_CLIENT_ID: ${{ secrets.COINMATE_CLIENT_ID }}
          COINMATE_PUBLIC_KEY: ${{ secrets.COINMATE_PUBLIC_KEY }}
          COINMATE_PRIVATE_KEY: ${{ secrets.COINMATE_PRIVATE_KEY }}
          PIE_ID: ${{ secrets.PIE_ID }}
          T212_WEIGHT: ${{ secrets.T212_WEIGHT }}
          BTC_WEIGHT: ${{ secrets.BTC_WEIGHT }}
          INVEST_AMOUNT: ${{ secrets.INVEST_AMOUNT }}
          INVEST_INTERVAL: ${{ secrets.INVEST_INTERVAL }}
        run: python main.py
